# Generated by Django 6.0.3 on 2026-03-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecerequise',
            name='format_accepte',
            field=models.CharField(choices=[('.pdf', 'PDF uniquement'), ('.pdf,.jpg,.png', 'PDF, JPG, PNG'), ('.pdf,.doc,.docx', 'PDF, DOC, DOCX'), ('*', 'Tous formats')], default='.pdf,.jpg,.png', max_length=50),
        ),
    ]
