# Generated by Django 6.0.3 on 2026-03-27 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_piecerequise_format_accepte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.TextField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configs_modifiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_plateforme',
            },
        ),
    ]
