# Generated by Django 6.0.3 on 2026-03-27 15:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_configplateforme'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapetraitement',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='etapes_pieces/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_RECEPTION', 'En réception SC'), ('PRET_IMPRESSION_DGI', 'Prêt à imprimer — DGI'), ('TRANSMISE_SG', 'Transmise SG'), ('EN_LECTURE_SG', 'En lecture SG'), ('TRANSMISE_MINISTRE', 'Transmise Ministre'), ('EN_LECTURE_MINISTRE', 'En lecture Ministre'), ('EN_INSTRUCTION_DGI', 'En instruction DGI'), ('EN_TRAITEMENT_DDPI', 'En traitement DDPI'), ('EN_TRAITEMENT_DDPI_BP', 'En traitement DDPI — Chef BP'), ('EN_TRAITEMENT_DDPI_US', 'En traitement DDPI — Chef Usines'), ('DOSSIER_INCOMPLET', 'Dossier incomplet'), ('VISITE_PROGRAMMEE', 'Visite programmée'), ('EN_COMMISSION_BP', 'En commission BP'), ('PV_COMITE_DEPOSE', 'PV comité BP déposé'), ('ATTENTE_QUITTANCE', 'En attente quittance paiement'), ('ACCORD_PRINCIPE', 'Accord de principe'), ('ARRETE_EN_COURS', 'Arrêté en rédaction'), ('SIGNATURE_DGI', 'Signature DGI'), ('SIGNATURE_MMI', 'Signature MMI / Ministre'), ('VALIDE', 'Validée'), ('REJETE', 'Rejetée')], default='SOUMISE', max_length=50),
        ),
        migrations.AlterField(
            model_name='etapetraitement',
            name='etape_code',
            field=models.CharField(choices=[('SC_RECEPTION', 'Accusé de réception numérique'), ('SC_TRANSMISSION_SG', 'Transmission au Secrétaire Général'), ('DGI_SEC_IMPRESSION', 'Dossier disponible pour impression'), ('SG_LECTURE', 'Prise en charge SG'), ('SG_TRANSMISSION_MIN', 'Transmission au Ministre'), ('SG_TRANSMISSION_DGI', 'Transmission directe DGI'), ('MIN_LECTURE', 'Prise en charge Ministre'), ('MIN_TRANSMISSION_DGI', 'Transmission DGI par Ministre'), ('DGI_INSTRUCTION', 'Instruction technique DGI'), ('DGI_TRANSMISSION_DDPI', 'Transmission à la DDPI'), ('DGI_SIGNATURE', 'Signature DGI'), ('DDPI_VERIFICATION', 'Vérification de complétude'), ('DDPI_INCOMPLET', 'Dossier incomplet — retour demandeur'), ('DDPI_CHEF_BP', 'Orientation Chef Service BP'), ('DDPI_CHEF_USINES', 'Orientation Chef Service Usines'), ('DDPI_VISITE', 'Visite des lieux programmée'), ('DDPI_PV_VISITE', 'PV de visite déposé'), ('DDPI_COMMISSION_BP', 'Dossier soumis en commission BP'), ('DDPI_PV_COMITE_BP', 'PV du comité BP déposé'), ('DDPI_QUITTANCE_BP', 'Quittance de paiement reçue'), ('DDPI_ACCORD_PRINCIPE', 'Accord de principe accordé'), ('DDPI_ARRETE_REDACTION', 'Redaction arrete en cours'), ('DDPI_REJET', 'Demande rejetée'), ('MMI_SIGNATURE', 'Signature officielle — Autorisation délivrée'), ('SYSTEME_VALIDATION', 'Validation système — document disponible')], max_length=60),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('DEMANDEUR', 'Demandeur'), ('SEC_CENTRAL', 'Agent Secrétariat Central'), ('SEC_GENERAL', 'Secrétaire Général'), ('MINISTRE', 'Ministre MMI — Signataire'), ('DGI_DIRECTEUR', "Directeur Général de l'Industrie"), ('DGI_SECRETARIAT', 'Secrétariat DGI'), ('DDPI_DIRECTEUR', 'Directeur DDPI'), ('DDPI_CHEF_BP', 'Chef Service Boulangeries / Pâtisseries'), ('DDPI_CHEF_USINES', 'Chef Service Usines Industrielles'), ('DDPI_AGENT', 'Agent DDPI'), ('SEC_COMITE_BP', 'Secrétaire du Comité BP'), ('MMI_SIGNATAIRE', 'Signataire MMI (fusionné Ministre)')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='QuittancePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='quittances/%Y/%m/')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('date_depot', models.DateTimeField(default=django.utils.timezone.now)),
                ('valide', models.BooleanField(default=False)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quittance', to='api.demande')),
                ('depose_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quittances_deposees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quittance_paiement',
            },
        ),
    ]
