# Generated by Django 6.0.3 on 2026-03-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_etapetraitement_piece_jointe_alter_demande_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorisation',
            name='activite',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='autorisation',
            name='raison_sociale',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='autorisation',
            name='source_historique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extensiondetail',
            name='autorisation_origine',
            field=models.ForeignKey(blank=True, help_text="Autorisation dont l'extension est demandée", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extensions', to='api.autorisation'),
        ),
        migrations.AddField(
            model_name='extensiondetail',
            name='numero_autorisation_original',
            field=models.CharField(blank=True, default='', help_text="Numéro de l'autorisation originale", max_length=80),
        ),
        migrations.AddField(
            model_name='renouvellementdetail',
            name='autorisation_origine',
            field=models.ForeignKey(blank=True, help_text='Autorisation dont le renouvellement est demandé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renouvellements', to='api.autorisation'),
        ),
        migrations.AddField(
            model_name='renouvellementdetail',
            name='numero_autorisation_original',
            field=models.CharField(blank=True, default='', help_text='Numéro saisi par le demandeur (validation manuelle possible)', max_length=80),
        ),
        migrations.AlterField(
            model_name='autorisation',
            name='demande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorisation', to='api.demande'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='activite',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='demande',
            name='adresse',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='demande',
            name='raison_sociale',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='demande',
            name='wilaya',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
