# Generated by Django 6.0.3 on 2026-04-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_autorisation_activite_autorisation_raison_sociale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='destinataire',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('ACTION_REQUISE', 'Action requise'), ('VALIDATION', 'Validée'), ('ACCORD_PRINCIPE', 'Accord de principe'), ('REJET', 'Rejetée'), ('INFO', 'Information')], default='ACTION_REQUISE', max_length=30),
        ),
    ]
