# Generated by Django 6.0.3 on 2026-04-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_notification_destinataire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('ar', 'Arabe')], default='fr', max_length=5),
        ),
    ]
